from typing import Any, Mapping, Optional, Union


class MonkeyPatch:
    def setattr(self, target: Any, name: str, value: Any = ..., raising: bool = ...) -> None: ...
    def delattr(self, target: Any, name: str = ..., raising: bool = ...) -> None: ...
    def setitem(self, dic: Mapping[Any, Any], name: Any, value: Any) -> None: ...
    def delitem(self, dic: Mapping[Any, Any], name: Any, raising: bool = ...) -> None: ...
    def setenv(self, name: str, value: str, prepend: Optional[str] = ...) -> None: ...
    def delenv(self, name: str, raising: bool = ...) -> None: ...
    def syspath_prepend(self, path: str) -> None: ...
    def chdir(self, path: str) -> None: ...
    def undo(self) -> None: ...