from ansible.playbook.base import Base as Base
from ansible.playbook.collectionsearch import CollectionSearch as CollectionSearch
from ansible.playbook.conditional import Conditional as Conditional
from ansible.playbook.taggable import Taggable as Taggable
from ansible.playbook.task import Task
from ansible.playbook.task_include import TaskInclude
from typing import Optional, Sequence, Union

class Block(Base, Conditional, CollectionSearch, Taggable):
    block: Sequence[Union[Block, Task]] = ...
    rescue: Sequence[Union[Block, Task]] = ...
    always: Sequence[Union[Block, Task]] = ...
    delegate_to: str = ...
    delegate_facts: bool = ...
    _parent: Optional[Union[Block, TaskInclude]] = ...