from ansible.playbook.base import FieldAttributeBase as FieldAttributeBase

class LoopControl(FieldAttributeBase):
    loop_var: str = ...
    index_var: str = ...
    label: str = ...
    pause: float = ...
    extended: bool = ...