from pathlib import Path

class Configuration:
    CASSETTE_LIBRARY_DIR: str = ...
    @property
    def cassette_library_dir(self) -> Path: ...
    @cassette_library_dir.setter
    def cassette_library_dir(self, value: Path) -> None: ...
