from .configure import Configuration as Configuration
from typing import Any, Dict, Optional, ContextManager

from requests import Session

class Betamax:
    def __init__(self, session: Session, cassette_library_dir: Optional[str] = ..., default_cassette_options: Dict[str, Any] = ...) -> None: ...
    session: Session = ...
    config: Configuration = ...
    @staticmethod
    def configure() -> ContextManager[Configuration]: ...

    def use_cassette(self, cassette_name: str, serialize_with: Optional[str] = ...) -> None:
        ...

    def start(self) -> None: ...
    def stop(self) -> None: ... 